name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: |
          python3 -m pip install --upgrade pip
          ls .
          pip install -r requirements.txt || true

      - name: Run test suite
        run: PYTHONPATH=tests/ python3 -m unittest discover